version: '3.8'

services:
  vectordb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8222:8222"
    volumes:
      - .:/app
      - ../uploads:/uploads
    command: uvicorn app:app --host 0.0.0.0 --port 8222 --reload
    environment:
      - PYTHONUNBUFFERED=1
